<script src="<?= js('vendor.min.js') ?>"></script>
<script src="<?= js('app.min.js') ?>"></script>
<script src="<?= js('axios.min.js') ?>"></script>
<script src="<?= js('store.modern.min.js') ?>"></script>
<script src="<?= js('jquery-3.6.1.min.js') ?>"></script>
<script src="<?= js('jquery-ui.min.js') ?>"></script>
<script src="<?= js('d3.v7.min.js') ?>"></script>
<script src="<?= js('jquery.tipsy.min.js') ?>"></script>
<script src="<?= js('chart.min.js') ?>"></script>
<script src="<?= js('leaflet.js') ?>"></script>
<script src="<?= js('leaflet-svg-shape-markers.min.js') ?>"></script>
<script src="<?= js('L.Path.DashFlow.js') ?>"></script>
<script src="<?= js('leaflet.control.select.src.js') ?>"></script>
<script src="<?= js('turf.min.js') ?>"></script>
<script src="<?= js('dexie.min.js') ?>"></script>