<script src="<?= js('vendor.min.js') ?>"></script>
<script src="<?= js('app.min.js') ?>"></script>
<script src="<?= js('axios.min.js') ?>"></script>
<script src="<?= js('store.modern.min.js') ?>"></script>
<script src="<?= js('jquery-3.6.1.min.js') ?>"></script>
<script src="<?= js('jquery-ui.min.js') ?>"></script>
<script src="<?= js('d3.v7.min.js') ?>"></script>
<script src="<?= js('jquery.tipsy.js') ?>"></script>
<script src="<?= js('chart.min.js') ?>"></script>